# -*- coding: utf-8 -*-
"""nano GPT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTKA6R5AFjrImhuWG6wVXZv8r-Dwi5B5
"""

"""
Project: Generative-Pretraining-Transformer-Scratchpad
Author: Jixuan Yao
Date: March 2026

LEARNING SOURCE:
This project is a dedicated study of the "Neural Networks: Zero to Hero" series
by Andrej Karpathy.
Course Reference: https://github.com/karpathy/ng-video-lecture

PURPOSE:
- Hand-coded reproduction: Every line is manually implemented while following
  the lecture to internalize the transformer architecture.
- Detailed Lab Notes

TECHNICAL FOCUS:
- Building a character-level language model from the ground up.
- Step-by-step evolution: From simple Bigram statistics to Multi-head Self-Attention.
- Data: Tiny Shakespeare dataset (Vocab size: 65).
"""


import os
import urllib.request
import torch

# data preparation
data_url = 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt'
save_path = "input.txt"

if not os.path.exists(save_path):
    print("Downlooading Datasets...")
    urllib.request.urlretrieve(data_url, save_path)
    print(f'Download sucessfully, saved in {save_path}')
else: print(f"Already exist{save_path}")

# -----------------------------------------------------------------------------------------------------------------------
# Read File

with open(save_path, 'r', encoding='utf-8' ) as f:
    text = f.read()

print('length of dataset:',len(text))

print(text[:1000])

# all the unique characters
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(' '.join(chars))
print(vocab_size)

# create a mapping from characters to integers
stoi = {ch:i for i,ch in enumerate(chars)} # 字符到数字的字典
itos = {i:ch for i,ch in enumerate(chars)}# 数字到字符的字典

encode = lambda s : [stoi[c] for c in s]
decode = lambda l : ''.join(itos[i] for i in l)

print(encode('hi, there'))
print(decode(encode('hi, there')))

# encode entire text dataset and store it into a torch.Tensor
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.type) # data tensor
# print(data[:1000])

# -----------------------------------------------------------------------------------------------------------------------
# split data into train and val sets
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

block_size = 8
print(train_data[: block_size+1])

x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[:t]
    print(f'when input is {context}, the target is {target}')

# -----------------------------------------------------------------------------------------------------------------------
print('-----------------------------------------------------------------------------------------------------------------------')
torch.manual_seed(1337)
batch_size = 4 #how much of independent sequences are proceed in parallel
block_size = 8 # maximum context length for predictions?

def get_batch(split):
    data = train_data if split == "train" else val_data
    # torch. randint(high, size) 生成一个张量，里面是随机数，范围是[0, high). len(data)-block_size 防止越界 ↓
    ix = torch.randint(len(data) - block_size, (batch_size,))   # batch size of random off sets into the training sets
    x = torch.stack([data[i:i+block_size] for i in ix]) # 将one dimensional tensor stack up into one tensor as rows
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

# only process one batch:
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]  # xb[b][0:t+1]  第b行的[0:t+1]
        target = xb[b,t]
        print(f'When input is {context}, the target is: {target}')

# 输出：
# inputs:
# torch.Size([4, 8])
# tensor([[24, 43, 58,  5, 57,  1, 46, 43],     # 整个张量是一个batch, each of row is a chunk of training set
#         [44, 53, 56,  1, 58, 46, 39, 58],
#         [52, 58,  1, 58, 46, 39, 58,  1],
#         [25, 17, 27, 10,  0, 21,  1, 54]])
# targets:
# torch.Size([4, 8])
# tensor([[43, 58,  5, 57,  1, 46, 43, 39],
#         [53, 56,  1, 58, 46, 39, 58,  1],
#         [58,  1, 58, 46, 39, 58,  1, 46],
#         [17, 27, 10,  0, 21,  1, 54, 39]])
# When input is tensor([24]), the target is: 24
# When input is tensor([24, 43]), the target is: 43
# When input is tensor([24, 43, 58]), the target is: 58
# When input is tensor([24, 43, 58,  5]), the target is: 5
# When input is tensor([24, 43, 58,  5, 57]), the target is: 57
# When input is tensor([24, 43, 58,  5, 57,  1]), the target is: 1
# When input is tensor([24, 43, 58,  5, 57,  1, 46]), the target is: 46
# When input is tensor([24, 43, 58,  5, 57,  1, 46, 43]), the target is: 43
# When input is tensor([44]), the target is: 44
# When input is tensor([44, 53]), the target is: 53
# When input is tensor([44, 53, 56]), the target is: 56
# When input is tensor([44, 53, 56,  1]), the target is: 1
# .... Four Batches


# -----------------------------------------------------------------------------------------------------------------------
print('-----------------------------------------------------------------------------------------------------------------------')

import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

# Bigram Model : 只看当前预测下一个
print(xb)  # Input to the Transformer

class BigramLanguageModel(nn.Module):
    def __init__ (self, vocab_size):
        super().__init__()
        # 创建一个trainnable lookup tableb 并自动随机初始化， 储存每个token对应下一个的概率
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) # 输出logits, P（y|x) = softmax(logits)

    def forward(self, idx, targets=None): #目前target optional
        # 一次取多个logits, idx 是Batch( 总共有多少个样本), Time（每个样本的长度） Tensor of integers
        # idx example: idx = [
                            # [0, 1, 2, 3],
                            # [4, 5, 6, 7]
                            # ]

        # logits shape: (B, T, C) C 是channel/vocab size
        logits = (self.token_embedding_table(idx))  # embedding table 是一个类而不是列表或字典，所以要用'()’
        if targets is None:
            loss = None

        else:
            B, T , C = logits.shape
            logits = logits.view(B*T, C) #将三维压缩成2维，才能计算cross_entropy
            targets = targets.view(B*T) #同理，二维压缩成一维
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens): # 最多生成多少个新token
        # idx is the (B, T) array of indeces in current context
        for _ in range(max_new_tokens):
            # get the prediction
            logits, loss = self(idx) # （B,T,C）  # 调用forward, loss 目前不用管 # currently a bit rediculous
            #把idx全部放进去但是bigram 只看最后一个。 但现在这里这样是因为后面会用上history
            logits = logits[: ,-1, :] # becomde (B,C)  只取最后一个时间的
            # softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # 对最后一个维度 C 做softmax  # bigram model 只取一个
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B,1)
            # append sample index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # 沿着一维（列方向）拼接
        return idx

# logits[0][0] = [0.5, 0.2, 0.1, ..., 0.0]  ← 样本0、位置0的50257个logits
# logits[0][1] = [0.1, 0.7, 0.1, ..., 0.1]  ← 样本0、位置1的50257个logits
# logits[0][2] = [...]
# logits[0][3] = [...]
# logits[1][0] = [...]
# ...


m = BigramLanguageModel(vocab_size) # vocab_size 65
logits, loss = m(xb, yb)
print(xb.shape) # [4,8] 4个独立句子，8个Token
print(yb.shape) # [4,8]
print(logits.shape) # logits 若未经过'压缩'：[4,8，65] 对4*8 = 32 个字符中的每一个都查出了65个数值，它们代表了下一个字符是vocabulary 1-65 个中每一个的可能性
                 # 这里是压缩后的所以是[32,65]
print(loss)
idx = torch.zeros((1,1), dtype=torch.long) # 一个样本一个token, indice 0对应第一个字符（see above)，类型是数据
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist())) # 循环100次，每次生成一个新token, 取第0个样本，然后将torch 张量转化为list

# 原来：[[0, a, b, c, ..., z]]  shape (1, 101)
#            ↓
#      取第0个
#            ↓
# 结果：[0, a, b, c, ..., z]   shape (101,)  ← 变成1维！


print('_' *10)

# create a pytorch parameter
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)
batch_size = 50
for step in range(10000):
    # sample a batch from data
    xb, yb = get_batch('train')

    #evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none = True) # 每次反向传播时，梯队会积累，因此要这样设置，清空后再进行下次
    loss.backward()
    optimizer.step() # 用梯度更新参数
print(loss.item()) # 把张量转换成普通Python数字

print(decode(m.generate(idx, max_new_tokens=300)[0].tolist()))

"""# The Mathematical Trick of self attention"""

torch.manual_seed(2002)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

# we want x[B,T] = mean_{i<=t} x[b,i]
xbow=torch.zeros((B,T,C)) # bow -> bag of words 对原数据的聚合处理
for b in range(B):
  for t in range(T):
    xprev = x[b,:t+1]
    xbow[b,t] = torch.mean(xprev, 0) # size (C,) 只有最后一维。 dim=0是行方向，对列求平均

x[0] #(T,C)

xbow[0]  # 第一行是avg( x[0]的row 1)=row1, 第二行avg(x[0]的row1 + x[0]的row 2 )......

# 理解矩阵乘法
torch.manual_seed(42)
a = torch.ones(3,3)
b = torch.randint(0,10,(3,2)).float()
c = a @ b # 乘
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)